services:

  db:
    image: "postgres:15"
    environment:
      - POSTGRES_DB=habit-tracker
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

volumes:
  postgres-data:
